let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" basics
syntax on
filetype plugin on
set background=dark
set clipboard=unnamedplus
set hidden
set wildmenu
set incsearch
set hlsearch
set path+=**
set dir="~/.vim/"
set conceallevel=2

" editor {{{
"
set tabstop=4
set shiftwidth=4
set expandtab
set tw=80
set nowrap
set nu rnu
set scrolloff=10
set foldmethod=marker
" }}}

" plugins {{{
call plug#begin()
    Plug 'gboncoffee/run.vim'
    Plug 'preservim/NERDTree'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-rsi'
    Plug 'yegappan/grep'
    Plug 'jiangmiao/auto-pairs'
    Plug 'lervag/vimtex'
call plug#end()
" }}}

" maps {{{
"
nnoremap <Tab>   :bn<CR>
nnoremap <S-Tab> :bp<CR>
nnoremap <C-l>   :nohl<CR>

nnoremap <Space><Enter> :Run<CR>
nnoremap <Space>cp      :Run python<CR>
nnoremap <Space>cj      :Run nodejs<CR>
nnoremap <Space>ch      :Run ghci<CR>
nnoremap <Space>cl      :Run lua<CR>
nnoremap <Space>ct      :Run htop<CR>
nnoremap <Space>cm      :Run ncmpcpp<CR>

nnoremap <Space>b       :Compile<CR>
nnoremap <Space>r       :Compile<CR>
nnoremap <Space>a       :Compile<CR>

nnoremap <Space>n :e .<CR>
nnoremap <Space>g :Git<CR><C-w>o
nnoremap <Space>/ :Rgrep<CR>
nnoremap <Space>f :find<Space>
" }}}

" autocmds/functions {{{
"
function SetNumbersAndQ()
    if index(['qf', 'fugitive', 'gitcommit', 'run-compiler', 'man', 'help', 'nerdtree'], &filetype) >= 0
        set nonu nornu
        nnoremap <buffer> q :bd<CR>
    else
        set nu rnu
    endif
endfunction
augroup Autocmds
    autocmd!
    autocmd BufEnter * call SetNumbersAndQ()
    autocmd FileType * call SetNumbersAndQ()
augroup END
" }}}

" colors {{{
"
hi Statement    ctermfg=Blue
hi LineNrAbove  ctermfg=LightBlue
hi LineNrBelow  ctermfg=LightBlue
hi Comment      ctermfg=Blue cterm=italic,bold
hi LineNr       ctermfg=Blue cterm=italic,bold
hi Identifier   ctermfg=NONE cterm=NONE
hi Folded       ctermfg=LightBlue ctermbg=Black
hi StatusLine   ctermfg=Black ctermbg=White
hi StatusLineNC ctermfg=Black ctermbg=Grey
hi VertSplit    ctermfg=Black ctermbg=White
hi WildMenu     ctermbg=Blue
hi Search       ctermbg=DarkMagenta ctermfg=Black
hi Visual       ctermbg=DarkMagenta
hi MatchParen   ctermbg=DarkMagenta
hi CursorLine   ctermbg=Black cterm=NONE 
" }}}

" NERDTree {{{
"
let g:NERDTreeShowHidden=1
let g:NERDTreeAutoCenter=1
let g:NERDTreeAutoCenterThreshold=10
let g:NERDTreeNaturalSort=1
let g:NERDTreeSortHiddenFirst=1
let g:NERDTreeChDirMode=2
let g:NERDTreeHighlightCursorline=1
let g:NERDTreeHijackNetrw=1
let g:NERDTreeBookmarksFile="~/.vim/nerdtree_bookmarks"
let g:NERDTreeShowLineNumbers=0
let g:NERDTreeWinPos='right'
let g:NERDTreeWinSize=30
let g:NERDTreeMinimalUI=1
let g:NERDTreeMinimalMenu=1
let g:NERDTreeCascadeSingleChildDir=0
let g:NERDTreeCreatePrefix='silent keepalt keepjumps'
let g:NERDTreeQuitOnOpen=1

let g:NERDTreeMapActivateNode='<Enter>'
let g:NERDTreeMapPreview='<A-Enter>'
let g:NERDTreeMapUpdir='h'
let g:NERDTreeMapRefreshRoot='<C-r>'
let g:NERDTreeMapToggleHidden='a'
let g:NERDTreeMapQuit='q'
let g:NERDTreeMapChangeRoot='l'
let g:NERDTreeMapMenu='m'
" }}}
